/**
 * Ralph Loop GitHub issue reporting module.
 *
 * Handles creating and updating the fitness tracking issue on GitHub, posting
 * per-evaluation comments, and generating the markdown bodies used for those
 * posts.  All GitHub interactions go through the `gh` CLI to leverage the
 * user's existing authentication.
 */

import { execSync } from "child_process";
import { tmpdir } from "os";
import { join } from "path";
import { writeFileSync } from "fs";
import {
  generateCiBlockedComment,
  generateCiCommentSummary,
  isCiBroken,
  type CiStatus,
} from "./ci-gating";
import type { Evaluation, FitnessScores, RalphState } from "./state";

/** Temporary file used to pass markdown bodies to `gh` via `--body-file`. */
const BODY_TMP = join(tmpdir(), "ralph-gh-body.md");

/**
 * Render a block-bar trend chart from past evaluations.
 *
 * @param evaluations - Ordered list of past evaluations.
 * @returns Markdown code block with ASCII bars.
 */
export function generateTrendChart(evaluations: Evaluation[]): string {
  if (evaluations.length === 0) return "No evaluations yet.";

  const lines = evaluations.map((e) => {
    const bar = "█".repeat(Math.round(e.scores.aggregate / 5));
    const empty = "░".repeat(20 - Math.round(e.scores.aggregate / 5));
    return `Iter ${String(e.iteration).padStart(3)}: ${bar}${empty} ${e.scores.aggregate}/100 (${e.model})`;
  });

  return "```\nFitness Trend:\n" + lines.join("\n") + "\n```";
}

/**
 * Render a per-model average score comparison table.
 *
 * @param evaluations - Ordered list of past evaluations.
 * @returns Markdown table rows.
 */
export function generateModelComparison(evaluations: Evaluation[]): string {
  const modelScores: Record<string, number[]> = {};
  for (const e of evaluations) {
    if (!modelScores[e.model]) modelScores[e.model] = [];
    const arr = modelScores[e.model];
    if (arr) arr.push(e.scores.aggregate);
  }

  const rows = Object.entries(modelScores).map(([model, scores]) => {
    const avg = Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
    return `| ${model} | ${scores.length} | ${avg}/100 |`;
  });

  return (
    "| Model | Evals | Avg Score |\n|-------|-------|-----------|\n" +
    rows.join("\n")
  );
}

/**
 * Generate the full GitHub issue body for the tracking issue.
 *
 * The body includes a trend chart, evaluation history table, and model
 * comparison summary. It is updated after every fitness evaluation via
 * `gh issue edit`.
 *
 * @param evaluations - All evaluations to display in the body.
 * @returns Markdown string suitable for posting as an issue body.
 */
export function generateIssueBody(evaluations: Evaluation[]): string {
  return `# Ralph Loop Fitness Tracking

This issue tracks the fitness of the \`gh-attach\` implementation across Ralph Loop iterations.
Each comment represents a fitness evaluation at a specific iteration.

## Trend

${generateTrendChart(evaluations)}

## Evaluation History

| Iter | Model | Spec | Tests | Quality | Build | Aggregate |
|------|-------|------|-------|---------|-------|-----------|
${evaluations.map((e) => `| ${e.iteration} | ${e.model} | ${e.scores.specCompliance} | ${e.scores.testCoverage} | ${e.scores.codeQuality} | ${e.scores.buildHealth} | **${e.scores.aggregate}** |`).join("\n")}

## Model Comparison

${generateModelComparison(evaluations)}

---
*Auto-generated by ralph-loop.ts*`;
}

/**
 * Generate the markdown comment body for a single fitness evaluation.
 *
 * Posted as a new comment on the tracking issue after each evaluation run.
 * Includes dimension scores, an aggregate, CI status, and a collapsible
 * checklist accordion sorted by ascending score (worst items first).
 *
 * @param iteration - Current loop iteration number.
 * @param model - Model that ran this iteration.
 * @param scores - Fitness scores from the evaluation.
 * @param ciStatus - Current CI status for display.
 * @returns Markdown string suitable for posting as an issue comment.
 */
export function generateCommentBody(
  iteration: number,
  model: string,
  scores: FitnessScores,
  ciStatus: CiStatus,
): string {
  const sortedChecklist = [...(scores.checklist ?? [])].sort(
    (a, b) => a.score - b.score,
  );

  const checklistRows = sortedChecklist
    .map(
      (item) =>
        `| ${item.requirement} | ${item.score}/100 | ${item.reasoning.replace(/\|/g, "\\|")} |`,
    )
    .join("\n");

  const accordion =
    sortedChecklist.length > 0
      ? `<details>\n<summary>📋 Detailed Checklist Scoring (${sortedChecklist.length} items)</summary>\n\n| Requirement | Score | Reasoning |\n|-------------|-------|-----------|\n${checklistRows}\n\n</details>`
      : "_No checklist data available for this evaluation._";

  return `## Fitness Evaluation — Iteration ${iteration} — ${model}

> **Aggregate: ${scores.aggregate}/100** — ${scores.notes}

| Dimension | Score |
|-----------|-------|
| Spec Compliance | ${scores.specCompliance}/100 |
| Test Coverage | ${scores.testCoverage}/100 |
| Code Quality | ${scores.codeQuality}/100 |
| Build Health | ${scores.buildHealth}/100 |
| **Aggregate** | **${scores.aggregate}/100** |

**Model**: ${model}
**CI**: ${generateCiCommentSummary(ciStatus)}

${accordion}

---
*Auto-generated by ralph-loop.ts at ${new Date().toISOString()}*`;
}

/** Configuration needed by GitHub reporting functions. */
export interface GitHubReportingConfig {
  trackingRepo: string;
}

/**
 * Execute a `gh` CLI command with retry logic.
 *
 * Retries up to `maxAttempts` times with a synchronous busy-wait between
 * attempts.  This is intentional for a CLI tool where we want deterministic
 * retry behaviour without requiring an event loop.
 *
 * @param cmd - Full shell command to run (must be shell-safe).
 * @param maxAttempts - Maximum retry count (default 3).
 * @param delayMs - Milliseconds to wait between retries (default 2000).
 */
export function ghExecWithRetry(
  cmd: string,
  maxAttempts = 3,
  delayMs = 2000,
): void {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      execSync(cmd, { encoding: "utf-8", timeout: 30_000 });
      return;
    } catch (err) {
      if (attempt === maxAttempts) throw err;
      // Synchronous sleep — acceptable for a CLI tool
      const end = Date.now() + delayMs;
      while (Date.now() < end) {
        /* spin */
      }
    }
  }
}

/**
 * Write `body` to a temp file and run `cmd --body-file <tmp>`.
 *
 * Using `--body-file` avoids shell-quoting pitfalls with multiline markdown.
 *
 * @param cmd - `gh` command (without `--body-file`).
 * @param body - Markdown body to write.
 * @param retry - If true, use `ghExecWithRetry`; otherwise run once.
 */
export function ghWithBodyFile(cmd: string, body: string, retry = false): void {
  writeFileSync(BODY_TMP, body, "utf-8");
  const fullCmd = `${cmd} --body-file ${JSON.stringify(BODY_TMP)}`;
  if (retry) {
    ghExecWithRetry(fullCmd);
  } else {
    execSync(fullCmd, { encoding: "utf-8", timeout: 30_000 });
  }
}

/**
 * Post a fitness evaluation result to the GitHub tracking issue.
 *
 * On the first call (when `state.trackingIssueNumber` is null) a new issue is
 * created with the labels `ralph-loop` and `automated`. Subsequent calls post
 * a comment and update the issue body.
 *
 * Mutates `state.trackingIssueNumber` when a new issue is created.
 *
 * @param state - Current Ralph Loop state (mutated when issue is created).
 * @param config - Configuration including `trackingRepo`.
 * @param scores - Fitness scores from the evaluation.
 * @param iteration - Current iteration number.
 * @param model - Model that ran this iteration.
 * @param logFn - Optional logger callback (defaults to console.error).
 */
export async function postToGitHub(
  state: RalphState,
  config: GitHubReportingConfig,
  scores: FitnessScores,
  iteration: number,
  model: string,
  logFn: (msg: string, level: string) => void = (msg, level) =>
    console.error(`[${level}] ${msg}`),
): Promise<void> {
  if (!config.trackingRepo) {
    logFn("No trackingRepo configured, skipping GitHub posting", "WARN");
    return;
  }

  try {
    // Create tracking issue on first run
    if (!state.trackingIssueNumber) {
      const result = execSync(
        `gh issue create --repo "${config.trackingRepo}" ` +
          `--title "[Ralph Loop] Fitness Tracking" ` +
          `--label "ralph-loop" --label "automated"`,
        { encoding: "utf-8", timeout: 30_000 },
      );
      const match = result.match(/\/issues\/(\d+)/);
      if (match && match[1]) {
        state.trackingIssueNumber = parseInt(match[1], 10);
        logFn(`Created tracking issue #${state.trackingIssueNumber}`, "GITHUB");
      }
    }

    if (state.trackingIssueNumber) {
      // Post per-evaluation comment (uses --body-file to preserve newlines)
      const comment = generateCommentBody(
        iteration,
        model,
        scores,
        state.ciStatus,
      );
      ghWithBodyFile(
        `gh issue comment ${state.trackingIssueNumber} --repo "${config.trackingRepo}"`,
        comment,
        true,
      );

      // Update issue body with rolling trend chart (also via --body-file)
      const body = generateIssueBody(state.evaluations);
      ghWithBodyFile(
        `gh issue edit ${state.trackingIssueNumber} --repo "${config.trackingRepo}"`,
        body,
        true,
      );

      logFn(
        `Posted evaluation comment to issue #${state.trackingIssueNumber} (${scores.checklist.length} checklist items)`,
        "GITHUB",
      );
    }
  } catch (err) {
    logFn(`Failed to post to GitHub: ${err}`, "ERROR");
  }
}

/**
 * Post a CI-blocked notification comment to the tracking issue.
 *
 * Skips if: CI is not broken, the issue hasn't been created yet, or a
 * notification was already posted for this iteration.
 *
 * @param state - Current loop state (mutated to record notification).
 * @param config - Configuration including `trackingRepo`.
 * @param iteration - Current iteration number.
 * @param logFn - Optional logger.
 */
export async function postCiBlockedNotification(
  state: RalphState,
  config: GitHubReportingConfig,
  iteration: number,
  logFn: (msg: string, level: string) => void = (msg, level) =>
    console.error(`[${level}] ${msg}`),
): Promise<void> {
  if (
    !config.trackingRepo ||
    !state.trackingIssueNumber ||
    !isCiBroken(state.ciStatus) ||
    state.ciLastBlockedNotification === iteration
  ) {
    return;
  }

  try {
    const body = generateCiBlockedComment(iteration, state.ciStatus);
    ghWithBodyFile(
      `gh issue comment ${state.trackingIssueNumber} --repo "${config.trackingRepo}"`,
      body,
      true,
    );
    state.ciLastBlockedNotification = iteration;
  } catch (err) {
    logFn(`Failed to post CI blocked notification: ${err}`, "ERROR");
  }
}
